package com.aital.doskaykt.models

data class Post(
    val bgColor: String,
    val categoryId: Int,
    val categoryName: String,
    val favorites: Int,
    val hasWhatsapp: Boolean,
    val id: Int,
    val isActive: Boolean,
    val isAgency: Boolean,
    val isExpress: Boolean,
    val isOwner: Boolean,
    val isVerified: Boolean,
    val isVip: Boolean,
    val latitude: Double,
    val longitude: Double,
    val options: List<Option>,
    val phone: String,
    val picsUrl: List<PicsUrl>,
    val price: String,
    val publicDate: String,
    val rubricId: Int,
    val rubricName: String,
    val soldCount: Int,
    val stickers: List<Sticker>,
    val subcategoryId: Int,
    val subcategoryName: String,
    val text: String,
    val timestamp: Long,
    val title: String,
    val titleView: String,
    val video: List<Any>,
    val views: Int
):java.io.Serializable